server:
  port: 8086
  
info:
  app:
    name: Stock Service
    description: 
    version: 0.0.1
    
spring:
  application:
    name: stock-microservice
  config:
    import: optional:configserver:http://localhost:8888/ 

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
        exclude: 

