server:
  port: 8086
  
info:
  app:
    name: Stock Service
    description: 
    version: 0.0.1
    
spring:
  application:
    name: Stock Service
  data:
    mongodb:
      uri: mongodb+srv://riya_mittal:riya%40123%21%21@cluster0.c4pby.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: StockDB

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
        exclude: 
        
logging:
  level:
    root: INFO
    org.package: INFO
